<a href="https://colab.research.google.com/github/Ashish-Gulab/Numpy-Python-Library-/blob/main/numpy_and_pandas_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")


Hello


NUMPY MODULE(Arrays and Matrices)

In [ ]:
import numpy as np

In [ ]:
a=np.array([2,5,3,8,6,5,4,3])

In [ ]:
print(a)

[2 5 3 8 6 5 4 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# accessing array elements
a[0]

2

In [ ]:
a[3]

8

In [ ]:
a[3]=200

In [ ]:
print(a)

[  2   5   3 200   6   5   4   3]


In [ ]:
b=np.array([[3,35,56],[4,5,3]])

In [ ]:
b[0][1]

35

In [ ]:
print(b)

[[ 3 35 56]
 [ 4  5  3]]


In [ ]:
print(b.shape) # Shape is used for getting the number of rows and columns

(2, 3)


In [ ]:
print(b.size) #Size is used to get the number of total elements in the array

6


In [ ]:
mylist=np.arange(10) # Arange is used to get the number of elements started from 0 to the entered range

In [ ]:
print(mylist)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
l1=np.arange(1,11,2) # The array is starting from 1 and elements are inserted at a gap of 2

In [ ]:
l1

array([1, 3, 5, 7, 9])

In [ ]:
print(l1)

[1 3 5 7 9]


In [ ]:
a=np.zeros(7)
a

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
print(a)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 2-D Array
a=np.zeros((3,5))

In [ ]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
a=np.ones((3,5)) # "ones" is used for 1 as all the elements 

In [ ]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Random Function
# "random" is a class and inside the random we have various functions.
r=np.random.rand(5,4)

In [ ]:
r # default , it take the values between 0 and 1

array([[0.9301783 , 0.12575396, 0.41241209, 0.58858328],
       [0.55733624, 0.16333771, 0.69302096, 0.09086913],
       [0.61773945, 0.81109124, 0.64024423, 0.08390406],
       [0.24046523, 0.59542005, 0.40603708, 0.37664883],
       [0.68040698, 0.52815855, 0.25687186, 0.14972523]])

In [ ]:
print(r)

[[0.9301783  0.12575396 0.41241209 0.58858328]
 [0.55733624 0.16333771 0.69302096 0.09086913]
 [0.61773945 0.81109124 0.64024423 0.08390406]
 [0.24046523 0.59542005 0.40603708 0.37664883]
 [0.68040698 0.52815855 0.25687186 0.14972523]]


In [ ]:
r1=np.random.randint(20) # It will generate the random numbers between 0 and 20(both included)
r1

19

In [ ]:
# Return a number between 3 and 9(both included)
print(np.random.randint(3,9))

5


In [ ]:
r1=np.random.randint(5,50,dtype=np.uint8) # dtype is used for "data type"
r1

38

In [ ]:
x=np.array([[1,2],[3,4]])

y=np.array([[5,6],[7,8]])

print(x)

print(y)

print(x+y)
print(np.add(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


**PANDAS(DATA ANALYSIS)**

**Data Science**: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.                           
**Pandas**:
1. Pandas used mostly for Data Analysis, provides tools for data manipulation:
reshaping, merging, sorting, agression etc.
2. Allow handling missing data.
3. Pandas Library on top of Numpy, meaning Pandas needs Numpy to operate.
4. Pandas contain labelled data.
. Pandas is a python package that deals mostly with                             
  a. Series (1d array)                                                           
  b. DataFrames(2d labeled heterogenous array)                                       
  c. Panel (general 3d array)

In [ ]:
import pandas as pd

In [ ]:
a=np.array([10,20,30,40,50,60])
p=pd.Series(a)
print(p,type(p))
print(a,type(a))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64 <class 'pandas.core.series.Series'>
[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [ ]:
p[1:4]

1    20
2    30
3    40
dtype: int64

In [ ]:
p[2]

30

In [ ]:
p.max()

60

In [ ]:
p.median()

35.0

In [ ]:
# pandas to numpy
x=p.values
print(x,type(x))

[10 20 30 40 50 60] <class 'numpy.ndarray'>


In [ ]:
# Getting top five records, use head()
p.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
print(p.head(4))

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
# getting bottom five records, use tail()
p.tail()

1    20
2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
p.tail(4)

2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# We can add "\\" in place of "\" so if there is a gap in the name of the folder then it will adjust. csv is comma seperated values file.
# df is variable data frame

import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/Salaries.csv") 
# https://drive.google.com/file/d/1jURfIyENQoLUd_eaANscfajPoLcNBICS/view?usp=sharing

In [ ]:
df.describe

<bound method NDFrame.describe of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [ ]:
print(df)

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]


In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
df.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [ ]:
df.head(3)

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515

In [ ]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
df.ndim #number of dimentions that are rows and columns

2

In [ ]:
df.size # Total number elements

468

In [ ]:
df.shape #number of rows and number of columns

(78, 6)

In [ ]:
df.describe() # describe return the numerical values of data.

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
df['salary']

0     186960
1      93000
2     110515
3     131205
4     104800
       ...  
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
df['salary'].dtype

dtype('int64')

In [ ]:
df['salary'].max()

186960

In [ ]:
df.iloc[10:15,:]

rank discipline  phd  service   sex  salary
10      Prof          B   39       33  Male  128250
11      Prof          B   23       23  Male  134778
12  AsstProf          B    1        0  Male   88000
13      Prof          B   35       33  Male  162200
14      Prof          B   25       19  Male  153750

In [ ]:
df.iloc[10:15,3]

10    33
11    23
12     0
13    33
14    19
Name: service, dtype: int64

In [ ]:
df['rank'].count() # column

78

In [ ]:
df['service'].describe()

count    78.000000
mean     15.051282
std      12.139768
min       0.000000
25%       5.250000
50%      14.500000
75%      20.750000
max      51.000000
Name: service, dtype: float64

In [ ]:
# Find two list are circulary identical or not
# user input list1, list2
# list1=[10,20,30,40,50]
# list2=[30,40,50,10,20]

In [ ]:
df_g=df.groupby('rank') #df_g is variable "data frame group"

In [ ]:
df_g # It is an object if we it separately

In [ ]:
df_g.max()

discipline  phd  service   sex  salary
rank                                            
AssocProf          B   26       24  Male  119800
AsstProf           B   11        6  Male   97032
Prof               B   56       51  Male  186960

In [ ]:
df_g.mean() # It will give the groupwise mean

phd    service         salary
rank                                          
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [ ]:
df_g=df.groupby('sex')['salary'].mean() # We want mean salary for male and female

In [ ]:
df_g

sex
Female    101002.410256
Male      115045.153846
Name: salary, dtype: float64

In [ ]:
# Filtering 
df['salary']>160000

0      True
1     False
2     False
3     False
4     False
      ...  
73    False
74    False
75    False
76    False
77    False
Name: salary, Length: 78, dtype: bool

In [ ]:
df[df['salary']>160000]

rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
13  Prof          B   35       33    Male  162200
72  Prof          B   24       15  Female  161101

In [ ]:
df[df['discipline']=='A']['salary'].mean()

98331.11111111111

In [ ]:
df[df['salary']>100000].groupby('sex')['salary'].count()

sex
Female    21
Male      25
Name: salary, dtype: int64

In [ ]:
# Sorting :- "sort_values"
df_sorted = df.sort_values(by="service")

In [ ]:
df_sorted

rank discipline  phd  service     sex  salary
55  AsstProf          A    2        0  Female   72500
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000
..       ...        ...  ...      ...     ...     ...
40      Prof          A   39       36  Female  137000
27      Prof          A   45       43    Male  155865
36      Prof          B   45       45    Male  146856
0       Prof          B   56       49    Male  186960
9       Prof          A   51       51    Male   57800

[78 rows x 6 columns]